### ISSUE TITLE
setup.py error

### ISSUE THREAD

**Issue by jethornton** [Tijndagamer/bmp180#3]
I cloned to my pi 3 then chmod 744 setup.py then got this error
~/bmp180 $ ./setup.py
from: can't read /var/mail/setuptools
./setup.py: line 3: syntax error near unexpected token `('
./setup.py: line 3: `def readme():'
I also verified that python-smbus is already the newest version (3.1.2-3).

**Comment by m-rtijn** [comment]
The current `setup.py` lacks the `#!/usr/bin/python` line to enable you to chmod the file and run it like you did. If you follow the instructions in the `README.md` and run `python setup.py install` it should work correctly. If not, try running it using sudo.
